import { Promo } from "./types";

// Manually researched and cross-checked against multiple independent outlets (see README's
// "情報源について" section) as a baseline, shown alongside whatever the live scraper finds.
// As of 2026-08-18 the live scrapers (lib/scrapers/sevenEleven.ts, lawson.ts,
// familyMart.ts) parse the three chains' official sites directly, verified against their
// real HTML structure — so this is now purely insurance against a sparse or failed scrape,
// not the primary source.
//
// Only entries whose purchaseStart/purchaseEnd currently contains today are shown (see
// lib/scrapers/index.ts's isCurrentlyPurchasable) — a promo whose purchase window has
// already closed is stale even if its later redeemStart/redeemEnd window is still open.
// Keep past entries here (rather than deleting them) so the app doesn't need a manual
// prune every week; just add this week's new ones. Refresh periodically — ask Claude to
// re-research it once these numbers look stale.
export const SEED_PROMOS: Promo[] = [
  {
    id: "seed-seven-eleven-georgia",
    store: "seven-eleven",
    buyItem: "ジョージア アシャッチュ ピーチ／マンゴー 410ml",
    getItem: "ジョージア アシャッチュ ピーチ／マンゴー 410ml",
    buyPrice: null,
    getPrice: null,
    periodText: "購入期間 8/11(火)〜8/17(月) / 引換期間 8/18(火)〜8/31(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-31",
    sourceUrl: "https://www.sej.co.jp/cmp/plaichi.html",
  },
  {
    id: "seed-seven-eleven-bulgaria",
    store: "seven-eleven",
    buyItem: "明治 ブルガリア フローズンヨーグルトデザート 他",
    getItem: "明治 ブルガリア フローズンヨーグルトデザート 他",
    buyPrice: null,
    getPrice: null,
    periodText: "購入期間 8/13(木)〜8/19(水) / 引換期間 8/20(木)〜9/2(水)",
    purchaseStart: "2026-08-13",
    purchaseEnd: "2026-08-19",
    redeemStart: "2026-08-20",
    redeemEnd: "2026-09-02",
    sourceUrl: "https://www.sej.co.jp/cmp/plaichi.html",
  },
  {
    id: "seed-lawson-mitsuya",
    store: "lawson",
    buyItem: "アサヒ おいしい水天然水 グリーンコーラ 500ml／三ツ矢 ウルトラストロングレモン 600ml",
    getItem: "三ツ矢 とくのうまい りんごスカッシュ 500ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 〜8/31(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-31",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-lawson-monster",
    store: "lawson",
    buyItem: "アサヒ モンスターエナジー 355ml／500ml",
    getItem: "レインストーム トロピカル 250ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-lawson-pasta",
    store: "lawson",
    buyItem: "ローソン もっちり生パスタ（芳醇ボロネーゼ／濃厚カルボナーラ／海老トマトクリーム）",
    getItem: "明治 ブルガリア フローズンヨーグルトデザート 85ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-family-mart-nope",
    store: "family-mart",
    buyItem: "サントリー NOPE ギルティ炭酸 600ml",
    getItem: "ファミマル ペプシコーラ 600ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 8/18(火)7:00〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-wilkinson",
    store: "family-mart",
    buyItem: "アサヒ ウィルキンソン タンサン マスカットスカッシュ 490ml",
    getItem: "アサヒ ウィルキンソン タンサン マスカットスカッシュ 490ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 8/18(火)7:00〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-ayataka",
    store: "family-mart",
    buyItem: "コカ・コーラ 綾鷹／綾鷹 濃い緑茶 650ml",
    getItem: "コカ・コーラ 綾鷹／綾鷹 濃い緑茶 650ml",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 8/18(火)7:00〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-jagariko",
    store: "family-mart",
    buyItem: "カルビー じゃがりこ（たらこバター／細いやつサラダ）",
    getItem: "カルビー じゃがりこ（じゃがバター／チーズ）",
    buyPrice: null,
    getPrice: null,
    periodText: "発券期間 8/11(火)〜8/17(月) / 引換期間 8/18(火)7:00〜8/24(月)",
    purchaseStart: "2026-08-11",
    purchaseEnd: "2026-08-17",
    redeemStart: "2026-08-18",
    redeemEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
];
