import { Promo } from "./types";

// Manually researched and cross-checked against multiple independent outlets (see README's
// "情報源について" section) as a baseline, shown alongside whatever the live scraper finds.
// The live scraper's own selectors are best-effort guesses at page structures we couldn't
// verify directly, so this exists as insurance against a sparse or failed scrape rather
// than as the primary source. Entries whose periodEnd has passed are filtered out
// automatically — refresh this list periodically (ask Claude to re-research it).
export const SEED_PROMOS: Promo[] = [
  {
    id: "seed-seven-eleven-georgia",
    store: "seven-eleven",
    buyItem: "ジョージア アシャッチュ ピーチ／マンゴー 410ml",
    getItem: "ジョージア アシャッチュ ピーチ／マンゴー 410ml",
    price: null,
    periodText: "購入期間 8/11(火)〜8/17(月)・引換期間 8/18(火)〜8/31(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-31",
    sourceUrl: "https://www.sej.co.jp/cmp/plaichi.html",
  },
  {
    id: "seed-seven-eleven-solmac",
    store: "seven-eleven",
    buyItem: "ソルマック5 50ml／チオビタ・ドリンク 100ml",
    getItem: "チオビタ・ドリンク 100ml",
    price: null,
    periodText: "購入期間 8/13(木)〜8/19(水)・引換期間 8/20(木)〜9/2(水)",
    periodStart: "2026-08-13",
    periodEnd: "2026-09-02",
    sourceUrl: "https://www.sej.co.jp/cmp/plaichi.html",
  },
  {
    id: "seed-seven-eleven-bulgaria",
    store: "seven-eleven",
    buyItem: "明治 ブルガリア フローズンヨーグルトデザート 他",
    getItem: "明治 ブルガリア フローズンヨーグルトデザート 他",
    price: null,
    periodText: "購入期間 8/13(木)〜8/19(水)・引換期間 8/20(木)〜9/2(水)",
    periodStart: "2026-08-13",
    periodEnd: "2026-09-02",
    sourceUrl: "https://www.sej.co.jp/cmp/plaichi.html",
  },
  {
    id: "seed-lawson-mitsuya",
    store: "lawson",
    buyItem: "アサヒ おいしい水天然水 グリーンコーラ 500ml／三ツ矢 ウルトラストロングレモン 600ml",
    getItem: "三ツ矢 とくのうまい りんごスカッシュ 500ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 〜8/31(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-31",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-lawson-monster",
    store: "lawson",
    buyItem: "アサヒ モンスターエナジー 355ml／500ml",
    getItem: "レインストーム トロピカル 250ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-lawson-pasta",
    store: "lawson",
    buyItem: "ローソン もっちり生パスタ（芳醇ボロネーゼ／濃厚カルボナーラ／海老トマトクリーム）",
    getItem: "明治 ブルガリア フローズンヨーグルトデザート 85ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.lawson.co.jp/campaign/",
  },
  {
    id: "seed-family-mart-nope",
    store: "family-mart",
    buyItem: "サントリー NOPE ギルティ炭酸 600ml",
    getItem: "ファミマル ペプシコーラ 600ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 8/18(火)7:00〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-wilkinson",
    store: "family-mart",
    buyItem: "アサヒ ウィルキンソン タンサン マスカットスカッシュ 490ml",
    getItem: "アサヒ ウィルキンソン タンサン マスカットスカッシュ 490ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 8/18(火)7:00〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-ayataka",
    store: "family-mart",
    buyItem: "コカ・コーラ 綾鷹／綾鷹 濃い緑茶 650ml",
    getItem: "コカ・コーラ 綾鷹／綾鷹 濃い緑茶 650ml",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 8/18(火)7:00〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
  {
    id: "seed-family-mart-jagariko",
    store: "family-mart",
    buyItem: "カルビー じゃがりこ（たらこバター／細いやつサラダ）",
    getItem: "カルビー じゃがりこ（じゃがバター／チーズ）",
    price: null,
    periodText: "発券 8/11(火)〜8/17(月)・引換 8/18(火)7:00〜8/24(月)",
    periodStart: "2026-08-11",
    periodEnd: "2026-08-24",
    sourceUrl: "https://www.family.co.jp/campaign.html",
  },
];
